### PR TITLE
PascalCase eklendi

### PR DESCRIPTION
**Pull request by yavuztarhan**
ilk harfi büyük gerisi küçük yapan PascalCase eklendi,
alse added PascalCase

### CODE REVIEW

**Comment by ahmetaa** [comment]
What is the use-case for this?

**Comment by yavuztarhan** [comment]
> What is the use-case for this?

for names, Burcu, Ahmet....

**Comment by ahmetaa** [comment]
This is already available as `toTitleCase`

**Comment by ahmetaa** [comment]
Closing as this is already available.

**Pull request closed without merging**
